name: linters

on:
  push:
    branches: [main]
    tags: v*
  pull_request:

jobs:
  run_linters:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Prepare project for development
      run: |
        python -m pip install poetry
        python -m poetry install

    - name: Run black
      run: python -m poetry run black tsrc --check

    - name: Run isort
      run: python -m poetry run isort tsrc --check

    - name: Run flake8
      run: python -m poetry run flake8 tsrc

    - name: Run pypy
      run: python -m poetry run mypy  --color-output --pretty

    - name: Check that doc builds without warnings
      run: python -m poetry run mkdocs build
